### PR TITLE
Add optional shape check to data parser

### PR DESCRIPTION
**Pull request by lemmon-714**
as per https://github.com/spacebudz/lucid/issues/126

The core functionality stays the same, just refactored it since the branching got too big.
Deno tests run through, but I didn't add any of myself yet.

### CODE REVIEW

**Comment by lemmon-714** [comment]
testing rn

**Comment by lemmon-714** [comment]
Added Quickcheck style tests; succeeds

Screenshot 2022-12-10 at 18 12 43

**Comment by lemmon-714** [comment]
I'm rn adding the option to leave the lengths of lists/maps/constr-fields indeterminate, so no need to rush looking at it. Also have a hunch it's a bad approach in the first place, will see.

**Comment by lemmon-714** [comment]
Note that the regular tests - for the old stuff - still run. Still WIP ofc.

**Comment by lemmon-714** [comment]
Note on the last one: only works on lists of primitives thus far

**Comment by lemmon-714** [comment]
Works, only thing untested now is the strange SumType Shape thing. And containers of nonprimitives.

**Comment by GGAlanSmithee** [comment]
I pulled this branch locally and tested it. I don't have any meaningful or productive feedback at this point, but it's building and all tests are passing!

**Comment by lemmon-714** [comment]
The UInt8Array-tests still fail btw, which is almost certainly a testing-issue, not an implementation-issue.

**Comment by lemmon-714** [comment]
Come to think of it, it might be simpler to leave the existing parsing as it was before, and add my checks afterwards as a function PlutusData, Shape -> PlutusData.

**Comment by lemmon-714** [comment]
Result https://github.com/spacebudz/lucid/pull/132

**Pull request closed without merging**
