### PR TITLE
Unit->AssetClass, Assets->AssetValue, for consistency

### PR DESCRIPTION
**Pull request by micahkendall**
Plutus, Cardano use the "AssetClass" and "Value" names for these two classes, it is easier to understand lucid when moving over if naming is consistent.

### CODE REVIEW

**Comment by micahkendall** [comment]
Originally I was trying to only change internal api, but the change kind of forces an avalanche of other changes, which I believe are all handled by this PR.

**Comment by alessandrokonrad** [comment]
Hey thanks for the PR. I would disagree with the change `Assets` -> `Value`. I chose `Assets` because it represents a difference structure (flat structure of assets: asset_class => quantity) and not a map (policy_id => asset_name => quantity).

I also see now that changing from `Unit` -> `AssetClass` breaks quite a bit and makes some function names longer than I wish them to be.

**Comment by micahkendall** [comment]
> Hey thanks for the PR. I would disagree with the change `Assets` -> `Value`. I chose `Assets` because it represents a different structure (flat structure of assets: unit => quantity) and not a map (policy_id => asset_name => quantity).

map would be (policy_id, asset_name) => quantity, unit represents this anyway so it is the same thing. 

> I also see now that changing from `Unit` -> `AssetClass` breaks quite a bit and makes some function names longer than I wish them to be.

AssetClass can be shortened to Asset where suitable (I have chosen any function which peaks on the structure to be operating on the AssetClass, and others on the Asset). The longest function in this pr increases from 16 to 17 characters under this change (getUtxosWithUnit -> getUtxosWithAsset), and is still shorter than existing ones (nativeScriptFromJson, slotToBeginUnixTime, applyParamsToScript for examples). 

Both fromUnit, toUnit (fromAssetClass, toAssetClass) are for external api not internal, so little is broken by changing them. Blockfrost uses Asset instead of AssetClass, so maybe that justifies only using Asset in this api- if you say that AssetClass is the particular Plutus representation of the asset as a Haskell tuple (although I would argue this is really for length). 

Unit is a confusing name in of itself- I don't see any other Cardano api using this and it conflates easily with execution units, which was what I assumed the api was when I was looking for the asset helper functions.

I think the biggest issue is breaking existing code- this could be remedied with a deprecation process where old api points to new with warnings.

**Comment by alessandrokonrad** [comment]
> map would be (policy_id, asset_name) => quantity, unit represents this anyway so it is the same thing.

This is not true. Value is a double map. So a very different structure (not flat) and much harder to work with.

> AssetClass can be shortened to Asset where suitable

I'm okay with Asset instead of AssetClass. Blockfrost actually uses Asset and Unit. I took the Unit idea from them.

**Comment by micahkendall** [comment]
May come back to this if there is reason to refactor overall.

**Pull request closed without merging**
